[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "moseq2-pca"
dynamic = ["version"]
authors = [
    {name = "Datta Lab"}
]
description = "PCA and model-free changepoint analysis for MoSeq2."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dask>=2025.4.1",
    "distributed>=2025.4.1",
    "h5py>=3.13.0",
    "toml>=0.10.2",
]

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx-click", 
    "sphinx-rtd-theme"
]

[project.scripts]
moseq2-pca = "moseq2_pca.cli:cli"

# Optional development tools configuration
[tool.black]
line-length = 100
target-version = ['py311']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.setuptools.packages.find]
where = ["."]
include = ["moseq2_pca*"]

[tool.setuptools.dynamic]
version = {attr = "moseq2_pca.__version__"}
